// Mocks generated by Mockito 5.4.6 from annotations
// in my_project_management_app/test/ai_usage_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_project_management_app/core/models/ai_usage_record.dart'
    as _i4;
import 'package:my_project_management_app/core/repository/i_ai_usage_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IAiUsageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAiUsageRepository extends _i1.Mock
    implements _i2.IAiUsageRepository {
  MockIAiUsageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logUsage(_i4.AiUsageRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#logUsage, [record]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.AiUsageRecord>> getUsageHistory({
    DateTime? from,
    DateTime? to,
    String? userId,
    String? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsageHistory, [], {
              #from: from,
              #to: to,
              #userId: userId,
              #projectId: projectId,
            }),
            returnValue: _i3.Future<List<_i4.AiUsageRecord>>.value(
              <_i4.AiUsageRecord>[],
            ),
          )
          as _i3.Future<List<_i4.AiUsageRecord>>);

  @override
  _i3.Future<Map<String, dynamic>> getUsageTotals({
    String? userId,
    String? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsageTotals, [], {
              #userId: userId,
              #projectId: projectId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
