// Mocks generated by Mockito 5.4.6 from annotations
// in my_project_management_app/test/dashboard_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_project_management_app/core/models/dashboard_types.dart'
    as _i5;
import 'package:my_project_management_app/core/repository/i_dashboard_repository.dart'
    as _i3;
import 'package:my_project_management_app/models/project_requirements.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProjectRequirements_0 extends _i1.SmartFake
    implements _i2.ProjectRequirements {
  _FakeProjectRequirements_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IDashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDashboardRepository extends _i1.Mock
    implements _i3.IDashboardRepository {
  MockIDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i3.DashboardItem>> loadConfig() =>
      (super.noSuchMethod(
            Invocation.method(#loadConfig, []),
            returnValue: _i4.Future<List<_i3.DashboardItem>>.value(
              <_i3.DashboardItem>[],
            ),
          )
          as _i4.Future<List<_i3.DashboardItem>>);

  @override
  _i4.Future<void> saveConfig(List<_i3.DashboardItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addItem(_i3.DashboardItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#addItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeItem(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [index]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateItemPosition(
    int? index,
    Map<String, dynamic>? position,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateItemPosition, [index, position]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.DashboardTemplate>> loadTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#loadTemplates, []),
            returnValue: _i4.Future<List<_i3.DashboardTemplate>>.value(
              <_i3.DashboardTemplate>[],
            ),
          )
          as _i4.Future<List<_i3.DashboardTemplate>>);

  @override
  _i4.Future<void> saveTemplates(List<_i3.DashboardTemplate>? templates) =>
      (super.noSuchMethod(
            Invocation.method(#saveTemplates, [templates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.SharedDashboard?> fetchSharedDashboard(String? shareId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSharedDashboard, [shareId]),
            returnValue: _i4.Future<_i5.SharedDashboard?>.value(),
          )
          as _i4.Future<_i5.SharedDashboard?>);

  @override
  _i4.Future<void> saveSharedDashboard(_i5.SharedDashboard? dashboard) =>
      (super.noSuchMethod(
            Invocation.method(#saveSharedDashboard, [dashboard]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSharedPermissions(
    String? shareId,
    Map<String, String>? permissions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSharedPermissions, [shareId, permissions]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.SharedDashboard?> loadLocalSharedDashboard(String? shareId) =>
      (super.noSuchMethod(
            Invocation.method(#loadLocalSharedDashboard, [shareId]),
            returnValue: _i4.Future<_i5.SharedDashboard?>.value(),
          )
          as _i4.Future<_i5.SharedDashboard?>);

  @override
  _i4.Future<void> saveLocalSharedDashboard(_i5.SharedDashboard? dashboard) =>
      (super.noSuchMethod(
            Invocation.method(#saveLocalSharedDashboard, [dashboard]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ProjectRequirements> fetchRequirements(
    String? projectCategory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRequirements, [projectCategory]),
            returnValue: _i4.Future<_i2.ProjectRequirements>.value(
              _FakeProjectRequirements_0(
                this,
                Invocation.method(#fetchRequirements, [projectCategory]),
              ),
            ),
          )
          as _i4.Future<_i2.ProjectRequirements>);

  @override
  _i2.ProjectRequirements parseRequirementsString(String? requirementsString) =>
      (super.noSuchMethod(
            Invocation.method(#parseRequirementsString, [requirementsString]),
            returnValue: _FakeProjectRequirements_0(
              this,
              Invocation.method(#parseRequirementsString, [requirementsString]),
            ),
          )
          as _i2.ProjectRequirements);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
